/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

export interface FileRoutesByPath {
  "/": {
    id: "/";
    path: "/";
    fullPath: "/";
    preLoaderRoute: typeof import("./router").indexRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
  "/login": {
    id: "/login";
    path: "/login";
    fullPath: "/login";
    preLoaderRoute: typeof import("./router").loginRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
  "/projects": {
    id: "/projects";
    path: "/projects";
    fullPath: "/projects";
    preLoaderRoute: typeof import("./router").tenantProjectsRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
  "/register": {
    id: "/register";
    path: "/register";
    fullPath: "/register";
    preLoaderRoute: typeof import("./router").registrationRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
}

export interface FileRoutesById {
  __root__: {
    id: "__root__";
    fullPath: "";
    preLoaderRoute: typeof import("./router").rootRoute;
    parentRoute: never;
  };
  "/": {
    id: "/";
    path: "/";
    fullPath: "/";
    preLoaderRoute: typeof import("./router").indexRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
  "/login": {
    id: "/login";
    path: "/login";
    fullPath: "/login";
    preLoaderRoute: typeof import("./router").loginRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
  "/projects": {
    id: "/projects";
    path: "/projects";
    fullPath: "/projects";
    preLoaderRoute: typeof import("./router").tenantProjectsRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
  "/register": {
    id: "/register";
    path: "/register";
    fullPath: "/register";
    preLoaderRoute: typeof import("./router").registrationRoute;
    parentRoute: typeof import("./router").rootRoute;
  };
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByPath;
  fullPaths: "/" | "/login" | "/projects" | "/register";
  fileRoutesByPath: FileRoutesByPath;
  fileRoutesById: FileRoutesById;
}

export interface RootRouteId {
  __root__: {
    id: "__root__";
    fullPath: "";
    preLoaderRoute: typeof import("./router").rootRoute;
    parentRoute: never;
  };
}

/* prettier-ignore-end */
